apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureclientsecrets.yale.broadinstitute.org
spec:
  group: yale.broadinstitute.org
  names:
    kind: AzureClientSecret
    listKind: AzureClientSecretList
    plural: azureclientsecrets
    shortNames:
    - acs
    singular: azureclientsecret
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              azureServicePrincipal:
                properties:
                  applicationID:
                    description: Azure Application ID of the Azure Service Principal
                    type: string
                  tenantID:
                    description: Azure Tenant ID of the Azure Service Principal
                    type: string
                required:
                - tenantID
                - applicationID
                type: object
              keyRotation:
                properties:
                  deleteAfter:
                    default: 14
                    description: Amount of days key is disabled before deleting
                    type: integer
                  disableAfter:
                    default: 10
                    description: Amount of days since last authentication before disabling
                    type: integer
                  ignoreUsageMetrics:
                    default: false
                    description: If true, ignore usage metrics for keys when deciding
                      if it is safe to disable (DDO-2864)
                    type: boolean
                  rotateAfter:
                    default: 69
                    description: Amount of days key is rotated after creation
                    type: integer
                type: object
              secret:
                properties:
                  clientSecretKeyName:
                    default: client_secret
                    description: Name of Secret data field that stores private key
                    type: string
                  name:
                    description: Name of Secret that houses SA. Secret name must end
                      in "sa-secret"
                    type: string
                required:
                - name
                type: object
              vaultReplications:
                items:
                  properties:
                    format:
                      description: |
                        Format of the key to store in Vault. One of:
                          `base64`: write the service account key JSON as a base64-encoded string value at the specified key
                          `plaintext`: write the service principals client secret as a plaintext string value at the specified key
                      enum:
                      - map
                      - json
                      - base64
                      - pem
                      - plaintext
                      type: string
                    key:
                      default: client_secret
                      description: Key in the Vault secret that should include the
                        SA key. (Ignored for `map` format).
                      type: string
                    path:
                      description: Path in Vault where the key should be written.
                        Note this will overwrite all data stored at the Vault path.
                      type: string
                  required:
                  - format
                  - path
                  type: object
                type: array
            required:
            - keyRotation
            - azureServicePrincipal
            - secret
            type: object
        type: object
