// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1beta1 "github.com/broadinstitute/yale/internal/yale/crd/api/v1beta1"
)

// AzureClientSecretInterface is an autogenerated mock type for the AzureClientSecretInterface type
type AzureClientSecretInterface struct {
	mock.Mock
}

type AzureClientSecretInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *AzureClientSecretInterface) EXPECT() *AzureClientSecretInterface_Expecter {
	return &AzureClientSecretInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, options
func (_m *AzureClientSecretInterface) Get(ctx context.Context, name string, options v1.GetOptions) (*v1beta1.AzureClientSecret, error) {
	ret := _m.Called(ctx, name, options)

	var r0 *v1beta1.AzureClientSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*v1beta1.AzureClientSecret, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *v1beta1.AzureClientSecret); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.AzureClientSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AzureClientSecretInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AzureClientSecretInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options v1.GetOptions
func (_e *AzureClientSecretInterface_Expecter) Get(ctx interface{}, name interface{}, options interface{}) *AzureClientSecretInterface_Get_Call {
	return &AzureClientSecretInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, options)}
}

func (_c *AzureClientSecretInterface_Get_Call) Run(run func(ctx context.Context, name string, options v1.GetOptions)) *AzureClientSecretInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *AzureClientSecretInterface_Get_Call) Return(_a0 *v1beta1.AzureClientSecret, _a1 error) *AzureClientSecretInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AzureClientSecretInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*v1beta1.AzureClientSecret, error)) *AzureClientSecretInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *AzureClientSecretInterface) List(ctx context.Context, opts v1.ListOptions) (*v1beta1.AzureClientSecretList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *v1beta1.AzureClientSecretList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*v1beta1.AzureClientSecretList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *v1beta1.AzureClientSecretList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.AzureClientSecretList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AzureClientSecretInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AzureClientSecretInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *AzureClientSecretInterface_Expecter) List(ctx interface{}, opts interface{}) *AzureClientSecretInterface_List_Call {
	return &AzureClientSecretInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *AzureClientSecretInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *AzureClientSecretInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *AzureClientSecretInterface_List_Call) Return(_a0 *v1beta1.AzureClientSecretList, _a1 error) *AzureClientSecretInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AzureClientSecretInterface_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*v1beta1.AzureClientSecretList, error)) *AzureClientSecretInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAzureClientSecretInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAzureClientSecretInterface creates a new instance of AzureClientSecretInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAzureClientSecretInterface(t mockConstructorTestingTNewAzureClientSecretInterface) *AzureClientSecretInterface {
	mock := &AzureClientSecretInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
