// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	v1 "github.com/broadinstitute/yale/internal/yale/crd/clientset/v1beta1"
	mock "github.com/stretchr/testify/mock"
)

// YaleCrdV1Interface is an autogenerated mock type for the YaleCrdV1Interface type
type YaleCrdV1Interface struct {
	mock.Mock
}

// GcpSaKeys provides a mock function with given fields:
func (_m *YaleCrdV1Interface) GcpSaKeys() v1.GcpSaKeyInterface {
	ret := _m.Called()

	var r0 v1.GcpSaKeyInterface
	if rf, ok := ret.Get(0).(func() v1.GcpSaKeyInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.GcpSaKeyInterface)
		}
	}

	return r0
}
