apiVersion: yale.broadinstitute.org/v1beta1
kind: AzureClientSecret
metadata:
  name: mf-test-acs
spec:
  azureServicePrincipal:
    applicationID: 291c47b8-e78b-4f50-a269-72bd99947016
    tenantID: fad90753-2022-4456-9b0a-c7e5b934e408
  keyRotation:
    deleteAfter: 14
    disableAfter: 10
    ignoreUsageMetrics: true
    rotateAfter: 69
  secret:
    clientSecretKeyName: test-client-secret
    name: mf-test-acs-secret
