apiVersion: yale.broadinstitute.org/v1beta1
kind: AzureClientSecret
metadata:
  name: mf-test-acs
spec:
  azureServicePrincipal:
    applicationID: <application_object_id>
    tenantID: <tenant_id>
  keyRotation:
    deleteAfter: 14
    disableAfter: 10
    ignoreUsageMetrics: true
    rotateAfter: 69
  secret:
    clientSecretKeyName: test-client-secret
    name: mf-test-acs-secret
  vaultReplications:
  - format: json
    path: /secret/dsde/terra/mf-testing/azure-client-secret
