package client

// Taken from disk manager
// https://github.com/broadinstitute/disk-manager/
import (
	monitoring "cloud.google.com/go/monitoring/apiv3/v2"
	"fmt"
	v1beta1crd "github.com/broadinstitute/yale/internal/yale/crd/api/v1beta1"
	v1beta1client "github.com/broadinstitute/yale/internal/yale/crd/clientset/v1beta1"
	vaultapi "github.com/hashicorp/vault/api"
	vaultapprole "github.com/hashicorp/vault/api/auth/approle"
	"golang.org/x/net/context"
	"google.golang.org/api/iam/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/kubernetes/scheme"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	restclient "k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"os"
)

const vaultRoleIdEnvVar = "VAULT_ROLE_ID"
const vaultSecretIdEnvVar = "VAULT_SECRET_ID"

// Clients struct containing the GCP and k8s clients used in this tool
type Clients struct {
	iam     *iam.Service
	metrics *monitoring.MetricClient
	k8s     kubernetes.Interface
	crd     v1beta1client.YaleCRDInterface
	vault   *vaultapi.Client
}

func NewClients(iam *iam.Service, metrics *monitoring.MetricClient, k8s kubernetes.Interface, crd v1beta1client.YaleCRDInterface, vault *vaultapi.Client) *Clients {
	return &Clients{
		iam:     iam,
		metrics: metrics,
		k8s:     k8s,
		crd:     crd,
		vault:   vault,
	}
}

// GetIAM will return a handle to the gcp IAM client generated by the builder
func (c *Clients) GetIAM() *iam.Service {
	return c.iam
}

// GetK8s will return  a handle to the kubernetes client generated by the builder
func (c *Clients) GetK8s() kubernetes.Interface {
	return c.k8s
}

// GetMetrics will return  a handle to the metrics client generated by the builder
func (c *Clients) GetMetrics() *monitoring.MetricClient {
	return c.metrics
}

// GetCRDs will return  a handle to the crd client generated by the builder
func (c *Clients) GetCRDs() v1beta1client.YaleCRDInterface {
	return c.crd
}

// GetVault will return  a handle to the vault client generated by the builder
func (c *Clients) GetVault() *vaultapi.Client {
	return c.vault
}

// Build creates the GCP and k8s clients used by this tool
// and returns both packaged in a single struct
func Build(local bool, kubeconfig string) (*Clients, error) {
	conf, err := buildKubeConfig(local, kubeconfig)
	if err != nil {
		return nil, fmt.Errorf("error building kube client: %v", err)
	}
	k8s, err := buildKubeClient(conf)
	if err != nil {
		return nil, fmt.Errorf("error building kube client: %v", err)
	}

	_iam, err := buildIAMClient()
	if err != nil {
		return nil, fmt.Errorf("error building GCP IAM client: %v", err)
	}
	metrics, err := buildMetricsClient()
	if err != nil {
		return nil, fmt.Errorf("error building GCP Cloud Monitoring Metric client: %v", err)
	}
	crd, err := buildCrdClient(conf)
	if err != nil {
		return nil, fmt.Errorf("error building GCP client: %v", err)
	}

	vault, err := buildVaultClient()
	if err != nil {
		return nil, fmt.Errorf("error building Vault client: %v", err)
	}
	return NewClients(_iam, metrics, k8s, crd, vault), nil
}

func buildKubeConfig(local bool, kubeconfig string) (*restclient.Config, error) {
	if local {
		config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
		if err != nil {
			return nil, fmt.Errorf("error building local k8s config: %v", err)
		}
		return config, nil
	}
	config, err := restclient.InClusterConfig()
	if err != nil {
		return nil, fmt.Errorf("error building in cluster k8s config: %v", err)
	}
	return config, nil
}

func buildKubeClient(config *restclient.Config) (*kubernetes.Clientset, error) {
	return kubernetes.NewForConfig(config)
}

func buildIAMClient() (*iam.Service, error) {
	ctx := context.Background()
	c, err := iam.NewService(ctx)
	if err != nil {
		return nil, fmt.Errorf("error creating iam api client: %v", err)
	}
	return c, nil
}

func buildMetricsClient() (*monitoring.MetricClient, error) {
	ctx := context.Background()
	c, err := monitoring.NewMetricClient(ctx)

	if err != nil {
		return nil, fmt.Errorf("error creating cloud monitoring metrics api client: %v", err)
	}
	return c, nil
}

func buildCrdClient(kubeconfig *restclient.Config) (*v1beta1client.YaleCRDClient, error) {
	if err := v1beta1crd.AddToScheme(scheme.Scheme); err != nil {
		return nil, err
	}

	return v1beta1client.NewForConfig(kubeconfig)
}

func buildVaultClient() (*vaultapi.Client, error) {
	client, err := vaultapi.NewClient(nil)
	if err != nil {
		return nil, fmt.Errorf("error constructing Vault client: %v", err)
	}

	roleID := os.Getenv(vaultRoleIdEnvVar)
	secretID := os.Getenv(vaultSecretIdEnvVar)

	if roleID != "" {
		if secretID == "" {
			return nil, fmt.Errorf("%s specified but no %s", vaultRoleIdEnvVar, vaultSecretIdEnvVar)
		}

		var auth *vaultapprole.AppRoleAuth
		auth, err = vaultapprole.NewAppRoleAuth(roleID, &vaultapprole.SecretID{FromString: secretID})
		if err != nil {
			return nil, fmt.Errorf("error authenticating Vault client: %v", err)
		}

		_, err = client.Auth().Login(context.Background(), auth)
		if err != nil {
			return nil, fmt.Errorf("error authenticating Vault client: %v", err)
		}
	}

	return client, nil
}
