// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	cache "github.com/broadinstitute/yale/internal/yale/cache"

	mock "github.com/stretchr/testify/mock"

	v1beta1 "github.com/broadinstitute/yale/internal/yale/crd/api/v1beta1"
)

// KeySync is an autogenerated mock type for the KeySync type
type KeySync struct {
	mock.Mock
}

type KeySync_Expecter struct {
	mock *mock.Mock
}

func (_m *KeySync) EXPECT() *KeySync_Expecter {
	return &KeySync_Expecter{mock: &_m.Mock}
}

// SyncIfNeeded provides a mock function with given fields: entry, gsks
func (_m *KeySync) SyncIfNeeded(entry *cache.Entry, gsks ...v1beta1.GCPSaKey) error {
	_va := make([]interface{}, len(gsks))
	for _i := range gsks {
		_va[_i] = gsks[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, entry)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cache.Entry, ...v1beta1.GCPSaKey) error); ok {
		r0 = rf(entry, gsks...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KeySync_SyncIfNeeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncIfNeeded'
type KeySync_SyncIfNeeded_Call struct {
	*mock.Call
}

// SyncIfNeeded is a helper method to define mock.On call
//   - entry *cache.Entry
//   - gsks ...v1beta1.GCPSaKey
func (_e *KeySync_Expecter) SyncIfNeeded(entry interface{}, gsks ...interface{}) *KeySync_SyncIfNeeded_Call {
	return &KeySync_SyncIfNeeded_Call{Call: _e.mock.On("SyncIfNeeded",
		append([]interface{}{entry}, gsks...)...)}
}

func (_c *KeySync_SyncIfNeeded_Call) Run(run func(entry *cache.Entry, gsks ...v1beta1.GCPSaKey)) *KeySync_SyncIfNeeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]v1beta1.GCPSaKey, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(v1beta1.GCPSaKey)
			}
		}
		run(args[0].(*cache.Entry), variadicArgs...)
	})
	return _c
}

func (_c *KeySync_SyncIfNeeded_Call) Return(_a0 error) *KeySync_SyncIfNeeded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KeySync_SyncIfNeeded_Call) RunAndReturn(run func(*cache.Entry, ...v1beta1.GCPSaKey) error) *KeySync_SyncIfNeeded_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewKeySync interface {
	mock.TestingT
	Cleanup(func())
}

// NewKeySync creates a new instance of KeySync. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKeySync(t mockConstructorTestingTNewKeySync) *KeySync {
	mock := &KeySync{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
