apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cronjobs.yale.rotate.com
spec:
  group: yale.rotate.com
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required: [ cronSpec, googleProject, serviceAccountNames ]
              type: object
              properties:
                containers:
                  type: object
                  properties:
                    image:
                      type: array
                      items:
                        env:
                          type: array
                      default: "Image tag here"
                          type: object
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /app/application_default_credentials.json
                cronSpec:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                  # runs every Monday
                  default: "0 3 * * 1"
                googleProject:
                  type: string
                serviceAccountNames:
                  type: array
                  items:
                    type: string
                    properties:
#                      k8's sa name
                      serviceAccountName:
  scope: Namespaced
  names:
    plural: cronjobs
    singular: cronjob
    kind: CronJob
    shortNames:
      - ct